### ISSUE TITLE
Thread safety. 

### ISSUE THREAD

**Issue by SmileGobo** [alxvasilev/cpp-promise#1]
The implementation has no mutexes. When calling resolve or reject, you must ensure that either then|fail will be called before or after.
Or was a different usage strategy intended?
I have synchronization failure by assertion https://github.com/alxvasilev/cpp-promise/blob/c85dd10144c2934b5a1a8bed284ea75b6ef73418/promise.hpp#L600
```
promise::Promise<int> loadDataFromSomeThread() {
    
     promise::Promise<int> pms;
     std::thread t{[pms](){
           //do some ....
     }};
     t.deatach();
     return pms;
}
int main() {
     std::promise<int> pms;     //it's waitable barier 
     auto f = pms.get_future();
     
     loadDataFromSomeThread()
         .then([&pms](int val){
             pms.set_value(val);
         })
        .fail([&pms](const promise::Error& err) { // There is a synchronization failure at this point
              pms.set_exception(new std::runtimer_error{err.msg()})
         )};
     std::cout << f.get() << std::endl;
     return 0;
}
```

**Comment by alxvasilev** [comment]
This promise implementation is not intended for threading - the idea is to use it in a single-threaded cooperative multitasking environment, similar to what javascript is. For inter-thread synchronization and communication, the standard C++ library already has facilities like std::promise and std::future.
